### PR TITLE
Fix People search (TV Shows), & include short films to search results

### PR DESCRIPTION
**Pull request by host505**

### CODE REVIEW

**Comment by nixgates** [comment]
I'm closing this pull request, I merged your larger one. 

You're a true champion. Thank you for helping out!

**Comment by host505** [comment]
Hmm, I undone this change in the other pr, for the sake of being 2 separate pr's, as the changes were unrelated.
I think you have to merge this one too (if you approve changes, that is).

**Comment by nixgates** [comment]
It looks fine, should be able to merge without much issue, unless you can think of something I haven't thought of?

Just wanted to check, what did you mean by: 

"separate repositories at least for the main parts -smi, pvi- "

I'm always keen to make things easier so if you got an idea, I'm all ears.

**Comment by host505** [comment]
Yes, looks fine, I thought the commits merged in-between would conflict, but no.

About the other thing I meant that separate repositories/dev branches for plugin.video.incursion and script.module.incursion (where the most/critical code resides) could help contributors submitting pr's, because now for a small change you have to fork the whole contents of the repository, and conflicts are more likely to happen in-between merges/commits.
Just a thought, thanks for what you do, take care.

**Pull request closed without merging**
